apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demoargo
  namespace: argocd
spec:
  project: spring-apps
  source:
    repoURL: https://github.com/xczdev/DemoManifests.git
    targetRevision: HEAD
    path: demoargo
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-apps-dev
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
